### ISSUE TITLE
Error while installing 'Spanish Language Pack for Visual Studio Code' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by ikevin92** [microsoft/vscode-loc#1166]
2022-11-14 12:05:36.014 [info] [perf] Render performance baseline is 16ms
2022-11-14 12:06:32.757 [info] Settings Sync: Updated current session b27e339a-52c6-4a89-a260-d87f411f3ac1
2022-11-14 12:06:40.394 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:40.505 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:40.635 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:40.843 [error] [Extension Host] (node:1065) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
2022-11-14 12:06:41.259 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:42.750 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:42.844 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:43.027 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:44.259 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:44.330 [warning] [ms-toolsai.vscode-jupyter-cell-tags]: View container 'jupyter' does not exist and all views registered to it will be added to 'Explorer'.
2022-11-14 12:06:44.385 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:45.363 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:45.402 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:45.403 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:46.171 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookWorkspaceEdit' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:06:46.171 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:06:46.171 [critical] Extension 'ms-vsliveshare.vsliveshare' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookContentProvider, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
product.json (WINS): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
2022-11-14 12:06:46.943 [warning] [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:06:47.553 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:47.554 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:47.806 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:47.806 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:47.908 [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:06:47.963 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:47.964 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:48.383 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:48.385 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:49.555 [critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:06:50.335 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:50.335 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:50.335 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:50.335 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:50.335 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:50.992 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:50.992 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:50.992 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:50.992 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:50.992 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:51.236 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:51.236 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:51.236 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:51.236 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:51.236 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:51.258 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:51.258 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:51.258 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:51.258 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:51.258 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:51.455 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:51.455 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:51.455 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:51.455 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:51.455 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:52.654 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:52.654 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:52.654 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:52.654 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:52.655 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:53.001 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:53.001 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:53.001 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:53.001 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:53.001 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:54.137 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:54.137 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:54.137 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:54.137 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: sass
2022-11-14 12:06:54.137 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:56.555 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:06:56.555 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:06:56.555 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:06:56.555 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:06:56.630 [warning] [redhat.fabric8-analytics]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:07:06.803 [error] [Extension Host] (node:1065) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2022-11-14 12:08:04.018 [critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:08:04.018 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookWorkspaceEdit' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:08:04.019 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:08:04.019 [critical] Extension 'ms-vsliveshare.vsliveshare' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookContentProvider, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
product.json (WINS): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
2022-11-14 12:08:04.036 [warning] [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:08:04.036 [warning] [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:08:04.036 [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:08:05.072 [error] [Extension Host] (node:1178) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
2022-11-14 12:08:05.436 [error] [Extension Host] (node:1178) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2022-11-14 12:08:05.475 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:08:05.475 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:08:05.475 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:08:05.475 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:08:07.908 [info] [perf] Render performance baseline is 16ms
2022-11-14 12:08:27.025 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:09:10.732 [error] CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:09:10.745 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:09:30.266 [error] Unable to install extension 'ms-ceintl.vscode-language-pack-es' as it is not compatible with VS Code '1.73.1'.: Error: Unable to install extension 'ms-ceintl.vscode-language-pack-es' as it is not compatible with VS Code '1.73.1'.
    at $.install (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:187065)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-14 12:09:50.536 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:09:59.859 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:10:41.031 [error] CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:10:41.042 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:12:08.475 [critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:12:08.475 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookWorkspaceEdit' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:12:08.475 [critical] Extension 'ms-vsliveshare.vsliveshare' wants API proposal 'notebookDocumentEvents' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2022-11-14 12:12:08.475 [critical] Extension 'ms-vsliveshare.vsliveshare' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookContentProvider, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
product.json (WINS): contribMenuBarHome, diffCommand, documentFiltersExclusive, fileSearchProvider, findTextInFiles, notebookCellExecutionState, notebookLiveShare, terminalDimensions, terminalDataWriteEvent, textSearchProvider
2022-11-14 12:12:08.504 [warning] [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:12:08.504 [warning] [redhat.vscode-xml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:12:08.505 [warning] [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
2022-11-14 12:12:09.434 [error] [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
2022-11-14 12:12:09.434 [error] [leonardnjura.skeletonsnippets]: Unknown language in `contributes.skeletonsnippets.language`. Provided value: javascriptreact 
2022-11-14 12:12:09.434 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: pug
2022-11-14 12:12:09.434 [error] [wscats.html-snippets]: Unknown language in `contributes.html-snippets.language`. Provided value: stylus
2022-11-14 12:12:10.312 [error] [Extension Host] (node:1303) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
2022-11-14 12:12:10.480 [error] [Extension Host] (node:1303) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
2022-11-14 12:12:10.985 [info] [perf] Render performance baseline is 16ms
2022-11-14 12:12:29.090 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
2022-11-14 12:13:07.834 [error] CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)
2022-11-14 12:13:07.849 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at G.extractAtLocation (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:193826)
    at async G.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:191248)
    at async V.extract (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:198187)
    at async V.doRun (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:199570)

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 741634).

**Comment by crsuzukimsft** [comment]
@TylerLeonhardt Could you review this issue?
